### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by joostruis** [arkanelinux/arkaneiso#1]
Hey Dennis,

I've been watching what you are doing and also find the os-installer an interesting project.
Now we are a Gentoo based project, formerly known as Sabayon Linux and I wanted to see if we could somehow implement this installer, at least for the GNOME based ISO. Would be nice to know if you can somehow help out and explore this possibility. 

Our project is mocaccino.org it is a layer based Linux distribution build from Gentoo Portage stable tree.
Myself I've been a repository maintainer for many years but when it comes down to the installer bits I am a bit clueless.
Perhaps we can help each other or even join forces.

Cheers!

**Comment by dennis1248** [comment]
Hey @joostruis,

Thank you for reaching out, it looks like a very interesting little project you have. Sure I'd love to help you out!

Do you have any preferred method of communication? For me personally it would be Steam since that is where I am always online, but I am fine with any alternatives if you have any suggestions. Once we have that set up we could maybe plan in a little video call and get to know each other.
